set_property SRC_FILE_INFO {cfile:C:/Projects/ERN24004/Experiments/13062024/Cora-Z7-07S-Pmod_Ad1/Cora-Z7-07S-Pmod_Ad1.srcs/constrs_1/imports/digilent-xdc-master/Cora-Z7-07S-Master.xdc rfile:../../../Cora-Z7-07S-Pmod_Ad1.srcs/constrs_1/imports/digilent-xdc-master/Cora-Z7-07S-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y18   IOSTANDARD LVCMOS33 } [get_ports {shield_spi_ss_io }]; #IO_L17P_T2_34 Sch=ja_p[1]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y19   IOSTANDARD LVCMOS33 } [get_ports {shield_spi_io1_io  }]; #IO_L17N_T2_34 Sch=ja_n[1]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y16   IOSTANDARD LVCMOS33 } [get_ports {  shield_spi_io0_io  }]; #IO_L7P_T1_34 Sch=ja_p[2]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y17   IOSTANDARD LVCMOS33 } [get_ports { shield_spi_sck_io  }]; #IO_L7N_T1_34 Sch=ja_n[2]
