domain_path: C:\Projects\ERN24004\Experiments\13062024\Cora-Z7-07S-Pmod_Ad1\sdk\platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
