domain_path: C:\Projects\ERN24004\Experiments\13062024\Cora-Z7-07S-Pmod_Ad1\sdk\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
